development:
  mongo:
    driver: "mongoose"
    uri:    "localhost/duxboard"
    debug:  true


production:
  mongo:
    driver: "mongoose"
    uri:    "ds039351.mongolab.com:39351/heroku_app34597789"
    debug:  true